name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: create dummy file
      run: echo toto>toto.txt
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: . # or path/to/artifact
