name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/upload-artifact@v3
      with:
        name: DiagnosticReports
        path: ~/Library/Logs/DiagnosticReports/
    - run: |
        ls -la /usr/local/opt/runner/provisioner/provisioner
        find . /usr/local/opt/runner/
        
